import PlaceholderImage from "./images/recipe-book.png";

export const Recipes = [
  {
    id: 1,
    title: "Classic Chocolate Chip Cookies",
    ingredients: [
      "1 cup unsalted butter",
      "1 cup granulated sugar",
      "1 cup brown sugar",
      "2 large eggs",
      "1 teaspoon vanilla extract",
      "3 cups all-purpose flour",
      "1 teaspoon baking soda",
      "1/2 teaspoon salt",
      "2 cups chocolate chips",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "In a large bowl, cream together butter, granulated sugar, and brown sugar until light and fluffy.",
      "Beat in eggs one at a time, then stir in vanilla.",
      "In a separate bowl, combine flour, baking soda, and salt. Gradually add dry ingredients to the butter mixture and mix well.",
      "Fold in chocolate chips.",
      "Drop rounded tablespoons of dough onto ungreased baking sheets.",
      "Bake for 9-11 minutes or until golden brown.",
      "Allow cookies to cool on baking sheets for 5 minutes before transferring to wire racks to cool completely.",
    ],
    image: PlaceholderImage,
    totalTime: 30,
    servings: 24,
    authenticity: 4,
    taste: 5,
    difficulty: 3,
    author: "Anonymous Baker",
    tags: ["cookies", "dessert", "chocolate", "baking"],
  },

  {
    id: 2,
    title: "Chicken Alfredo Pasta",
    ingredients: [
      "8 ounces fettuccine pasta",
      "2 boneless, skinless chicken breasts",
      "2 tablespoons olive oil",
      "4 cloves garlic, minced",
      "1 cup heavy cream",
      "1 cup grated Parmesan cheese",
      "1/4 cup chopped fresh parsley",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Cook fettuccine pasta according to package instructions. Drain and set aside.",
      "Season chicken breasts with salt and pepper. Heat olive oil in a large skillet over medium heat. Cook chicken until browned and cooked through, about 6-7 minutes per side. Remove chicken from skillet and let rest.",
      "In the same skillet, add minced garlic and cook until fragrant, about 1 minute.",
      "Pour in heavy cream and bring to a simmer. Stir in grated Parmesan cheese until sauce is smooth and creamy.",
      "Slice cooked chicken breasts into strips and add them to the skillet. Stir in cooked fettuccine pasta and toss to coat everything in the sauce.",
      "Garnish with chopped fresh parsley and serve hot.",
    ],
    image: PlaceholderImage,
    totalTime: 35,
    servings: 4,
    authenticity: 3,
    taste: 4,
    difficulty: 3,
    author: "Italian Food Lover",
    tags: ["pasta", "chicken", "creamy", "italian"],
  },

  {
    id: 3,
    title: "Caprese Salad",
    ingredients: [
      "4 large tomatoes",
      "8 ounces fresh mozzarella cheese",
      "1/4 cup fresh basil leaves",
      "2 tablespoons balsamic vinegar",
      "2 tablespoons extra virgin olive oil",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Slice tomatoes and fresh mozzarella cheese into thick slices.",
      "Arrange tomato and mozzarella slices on a serving plate, alternating them.",
      "Tear fresh basil leaves into smaller pieces and scatter them over the tomato and mozzarella slices.",
      "Drizzle balsamic vinegar and olive oil over the salad.",
      "Season with salt and pepper to taste.",
      "Serve immediately as a refreshing appetizer or side dish.",
    ],
    image: PlaceholderImage,
    totalTime: 15,
    servings: 4,
    authenticity: 4,
    taste: 5,
    difficulty: 1,
    author: "Healthy Eater",
    tags: ["salad", "appetizer", "fresh", "italian"],
  },

  {
    id: 4,
    title: "Guacamole",
    ingredients: [
      "3 ripe avocados",
      "1/4 cup diced onion",
      "1/4 cup chopped fresh cilantro",
      "1 jalapeno pepper, seeded and minced",
      "1 clove garlic, minced",
      "Juice of 1 lime",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Cut avocados in half, remove the pits, and scoop out the flesh into a bowl.",
      "Mash the avocado with a fork until desired consistency.",
      "Add diced onion, chopped cilantro, minced jalapeno pepper, and minced garlic to the bowl.",
      "Squeeze lime juice over the mixture and season with salt and pepper.",
      "Stir everything together until well combined.",
      "Taste and adjust seasonings as needed.",
      "Serve immediately with tortilla chips or as a topping for tacos, burritos, or sandwiches.",
    ],
    image: PlaceholderImage,
    totalTime: 10,
    servings: 4,
    authenticity: 4,
    taste: 5,
    difficulty: 1,
    author: "Mexican Cuisine Lover",
    tags: ["dip", "avocado", "mexican", "appetizer"],
  },

  {
    id: 5,
    title: "Greek Salad",
    ingredients: [
      "4 cups chopped romaine lettuce",
      "1 cup cherry tomatoes, halved",
      "1/2 cup sliced cucumber",
      "1/4 cup sliced red onion",
      "1/4 cup pitted Kalamata olives",
      "1/4 cup crumbled feta cheese",
      "2 tablespoons extra virgin olive oil",
      "1 tablespoon red wine vinegar",
      "1 teaspoon dried oregano",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a large bowl, combine chopped romaine lettuce, halved cherry tomatoes, sliced cucumber, sliced red onion, pitted Kalamata olives, and crumbled feta cheese.",
      "In a small bowl, whisk together olive oil, red wine vinegar, dried oregano, salt, and pepper to make the dressing.",
      "Drizzle the dressing over the salad and toss well to combine.",
      "Serve immediately as a light and refreshing salad.",
    ],
    image: PlaceholderImage,
    totalTime: 15,
    servings: 4,
    authenticity: 4,
    taste: 4,
    difficulty: 1,
    author: "Mediterranean Food Enthusiast",
    tags: ["salad", "vegetarian", "greek", "healthy"],
  },
  {
    id: 6,
    title: "Chicken Parmesan",
    ingredients: [
      "2 boneless, skinless chicken breasts",
      "1 cup bread crumbs",
      "1/2 cup grated Parmesan cheese",
      "1/2 teaspoon dried oregano",
      "1/2 teaspoon dried basil",
      "1/4 teaspoon garlic powder",
      "1/4 teaspoon salt",
      "1/4 teaspoon black pepper",
      "1/4 cup all-purpose flour",
      "1 large egg, beaten",
      "1 cup marinara sauce",
      "1 cup shredded mozzarella cheese",
      "Fresh basil leaves for garnish",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Place chicken breasts between two sheets of plastic wrap and pound them to an even thickness.",
      "In a shallow bowl, combine bread crumbs, Parmesan cheese, dried oregano, dried basil, garlic powder, salt, and black pepper.",
      "Dredge each chicken breast in flour, dip in beaten egg, and coat with the breadcrumb mixture.",
      "Heat olive oil in a large skillet over medium-high heat. Cook chicken until golden brown and crispy on both sides.",
      "Transfer chicken to a baking dish and spoon marinara sauce over each piece.",
      "Sprinkle shredded mozzarella cheese over the sauce.",
      "Bake for 20-25 minutes or until cheese is melted and bubbly.",
      "Garnish with fresh basil leaves and serve hot.",
    ],
    image: PlaceholderImage,
    totalTime: 45,
    servings: 2,
    authenticity: 3,
    taste: 4,
    difficulty: 3,
    author: "Italian Food Lover",
    tags: ["chicken", "italian", "main course"],
  },

  {
    id: 7,
    title: "Roasted Vegetables",
    ingredients: [
      "2 cups mixed vegetables (such as bell peppers, zucchini, carrots, and red onions), cut into bite-sized pieces",
      "2 tablespoons olive oil",
      "1 teaspoon dried thyme",
      "1 teaspoon dried rosemary",
      "1/2 teaspoon garlic powder",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat oven to 425°F (220°C).",
      "In a large bowl, toss mixed vegetables with olive oil, dried thyme, dried rosemary, garlic powder, salt, and pepper until well coated.",
      "Spread vegetables in a single layer on a baking sheet.",
      "Roast in the preheated oven for 20-25 minutes or until vegetables are tender and slightly caramelized, stirring once halfway through cooking.",
      "Serve as a side dish or as a base for grain bowls or salads.",
    ],
    image: PlaceholderImage,
    totalTime: 30,
    servings: 4,
    authenticity: 2,
    taste: 3,
    difficulty: 2,
    author: "Healthy Eater",
    tags: ["vegetables", "roasted", "healthy", "side dish"],
  },

  {
    id: 8,
    title: "Beef Stir-Fry",
    ingredients: [
      "1 pound beef sirloin, thinly sliced",
      "2 tablespoons soy sauce",
      "1 tablespoon cornstarch",
      "2 tablespoons vegetable oil",
      "2 cloves garlic, minced",
      "1 teaspoon grated ginger",
      "1 red bell pepper, thinly sliced",
      "1 cup broccoli florets",
      "1 cup sliced mushrooms",
      "1/4 cup oyster sauce",
      "1/4 cup beef broth",
      "2 green onions, sliced",
      "Cooked rice or noodles for serving",
    ],
    instructions: [
      "In a bowl, combine sliced beef with soy sauce and cornstarch. Toss to coat and let marinate for 10 minutes.",
      "Heat vegetable oil in a large skillet or wok over high heat.",
      "Add minced garlic and grated ginger to the skillet and stir-fry for 1 minute.",
      "Add marinated beef to the skillet and cook until browned and cooked through, about 3-4 minutes.",
      "Add sliced bell pepper, broccoli florets, and sliced mushrooms to the skillet. Stir-fry for an additional 2-3 minutes or until vegetables are tender-crisp.",
      "In a small bowl, whisk together oyster sauce and beef broth. Pour the sauce mixture into the skillet and stir to coat everything.",
      "Cook for 1-2 minutes or until the sauce has thickened.",
      "Garnish with sliced green onions and serve hot over cooked rice or noodles.",
    ],
    image: PlaceholderImage,
    totalTime: 25,
    servings: 4,
    authenticity: 3,
    taste: 4,
    difficulty: 3,
    author: "Asian Cuisine Lover",
    tags: ["beef", "stir-fry", "asian", "main course"],
  },

  {
    id: 9,
    title: "Vegetable Curry",
    ingredients: [
      "1 tablespoon vegetable oil",
      "1 onion, chopped",
      "2 cloves garlic, minced",
      "1 tablespoon grated ginger",
      "2 tablespoons curry powder",
      "1 can (14 ounces) coconut milk",
      "1 cup vegetable broth",
      "2 carrots, sliced",
      "1 bell pepper, chopped",
      "1 cup cauliflower florets",
      "1 cup green beans, trimmed",
      "1 cup frozen peas",
      "Salt and pepper to taste",
      "Fresh cilantro for garnish",
    ],
    instructions: [
      "Heat vegetable oil in a large pot or skillet over medium heat.",
      "Add chopped onion, minced garlic, and grated ginger to the pot. Cook until onion is translucent and fragrant, about 5 minutes.",
      "Stir in curry powder and cook for 1 minute to toast the spices.",
      "Pour in coconut milk and vegetable broth. Stir well to combine.",
      "Add sliced carrots, chopped bell pepper, cauliflower florets, and green beans to the pot.",
      "Bring the mixture to a boil, then reduce heat to low and simmer for 15-20 minutes or until vegetables are tender.",
      "Stir in frozen peas and cook for an additional 2-3 minutes.",
      "Season with salt and pepper to taste.",
      "Garnish with fresh cilantro and serve hot over steamed rice or with naan bread.",
    ],
    image: PlaceholderImage,
    totalTime: 40,
    servings: 4,
    authenticity: 3,
    taste: 4,
    difficulty: 2,
    author: "Vegetarian Cook",
    tags: ["vegetable", "curry", "vegan", "main course"],
  },

  {
    id: 10,
    title: "Berry Smoothie",
    ingredients: [
      "1 cup mixed berries (such as strawberries, blueberries, and raspberries)",
      "1 ripe banana",
      "1 cup plain Greek yogurt",
      "1/2 cup almond milk (or any milk of your choice)",
      "1 tablespoon honey (optional)",
      "Ice cubes",
    ],
    instructions: [
      "Place mixed berries, ripe banana, Greek yogurt, almond milk, and honey (if using) in a blender.",
      "Blend until smooth and creamy.",
      "Add ice cubes and blend again until desired consistency.",
      "Pour into glasses and serve immediately as a refreshing and nutritious smoothie.",
    ],
    image: PlaceholderImage,
    totalTime: 5,
    servings: 2,
    authenticity: 2,
    taste: 4,
    difficulty: 1,
    author: "Smoothie Lover",
    tags: ["smoothie", "berries", "healthy", "breakfast"],
  },

  {
    id: 11,
    title: "Shrimp Scampi",
    ingredients: [
      "1 pound large shrimp, peeled and deveined",
      "4 tablespoons butter",
      "4 cloves garlic, minced",
      "1/4 teaspoon red pepper flakes",
      "1/4 cup white wine",
      "2 tablespoons lemon juice",
      "1/4 cup chopped fresh parsley",
      "Salt and pepper to taste",
      "Cooked pasta for serving",
    ],
    instructions: [
      "In a large skillet, melt butter over medium heat.",
      "Add minced garlic and red pepper flakes to the skillet. Cook for 1-2 minutes until garlic is fragrant.",
      "Increase heat to high and add shrimp to the skillet. Cook until shrimp turn pink and opaque, about 2-3 minutes per side.",
      "Remove shrimp from the skillet and set aside.",
      "Pour white wine and lemon juice into the skillet. Cook for 2-3 minutes to reduce the liquid.",
      "Return cooked shrimp to the skillet. Stir in chopped fresh parsley and season with salt and pepper to taste.",
      "Cook for an additional 1-2 minutes to heat the shrimp through.",
      "Serve hot over cooked pasta.",
    ],
    image: PlaceholderImage,
    totalTime: 20,
    servings: 4,
    authenticity: 3,
    taste: 5,
    difficulty: 2,
    author: "Seafood Lover",
    tags: ["shrimp", "scampi", "seafood", "main course"],
  },

  {
    id: 12,
    title: "Mediterranean Quinoa Salad",
    ingredients: [
      "1 cup cooked quinoa",
      "1 cup cherry tomatoes, halved",
      "1/2 cucumber, diced",
      "1/4 cup diced red onion",
      "1/4 cup Kalamata olives, pitted and halved",
      "1/4 cup crumbled feta cheese",
      "2 tablespoons extra virgin olive oil",
      "2 tablespoons lemon juice",
      "1 teaspoon dried oregano",
      "Salt and pepper to taste",
      "Fresh parsley for garnish",
    ],
    instructions: [
      "In a large bowl, combine cooked quinoa, cherry tomatoes, diced cucumber, diced red onion, Kalamata olives, and crumbled feta cheese.",
      "In a small bowl, whisk together extra virgin olive oil, lemon juice, dried oregano, salt, and pepper to make the dressing.",
      "Pour the dressing over the quinoa mixture and toss well to combine.",
      "Garnish with fresh parsley and serve chilled as a refreshing salad or side dish.",
    ],
    image: PlaceholderImage,
    totalTime: 15,
    servings: 4,
    authenticity: 3,
    taste: 4,
    difficulty: 2,
    author: "Healthy Eater",
    tags: ["quinoa", "salad", "mediterranean", "healthy"],
  },

  {
    id: 13,
    title: "Honey Mustard Chicken",
    ingredients: [
      "4 boneless, skinless chicken breasts",
      "1/4 cup Dijon mustard",
      "2 tablespoons honey",
      "1 tablespoon lemon juice",
      "1 clove garlic, minced",
      "1/2 teaspoon dried thyme",
      "Salt and pepper to taste",
      "Fresh parsley for garnish",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "In a small bowl, whisk together Dijon mustard, honey, lemon juice, minced garlic, dried thyme, salt, and pepper.",
      "Place chicken breasts in a baking dish and spoon the honey mustard mixture over them, coating both sides.",
      "Bake for 25-30 minutes or until chicken is cooked through and no longer pink in the center.",
      "Garnish with fresh parsley and serve hot as a flavorful and easy main course.",
    ],
    image: PlaceholderImage,
    totalTime: 40,
    servings: 4,
    authenticity: 2,
    taste: 4,
    difficulty: 2,
    author: "Home Cook",
    tags: ["chicken", "honey mustard", "main course"],
  },

  {
    id: 14,
    title: "Caprese Skewers",
    ingredients: [
      "1 pint cherry tomatoes",
      "8 ounces fresh mozzarella balls",
      "Fresh basil leaves",
      "Balsamic glaze for drizzling",
      "Wooden skewers",
    ],
    instructions: [
      "Thread a cherry tomato onto a wooden skewer.",
      "Next, add a fresh mozzarella ball onto the skewer.",
      "Finish with a fresh basil leaf.",
      "Repeat the process with the remaining ingredients.",
      "Arrange the skewers on a serving platter.",
      "Drizzle balsamic glaze over the skewers.",
      "Serve as a colorful and delicious appetizer or snack.",
    ],
    image: PlaceholderImage,
    totalTime: 15,
    servings: 4,
    authenticity: 2,
    taste: 5,
    difficulty: 1,
    author: "Appetizer Lover",
    tags: ["caprese", "skewers", "appetizer", "italian"],
  },

  {
    id: 15,
    title: "Chocolate Chip Cookies",
    ingredients: [
      "1 cup unsalted butter, softened",
      "1 cup granulated sugar",
      "1 cup packed brown sugar",
      "2 large eggs",
      "1 teaspoon vanilla extract",
      "3 cups all-purpose flour",
      "1 teaspoon baking soda",
      "1/2 teaspoon salt",
      "2 cups chocolate chips",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "In a large bowl, cream together softened butter, granulated sugar, and packed brown sugar until light and fluffy.",
      "Beat in eggs, one at a time, followed by vanilla extract.",
      "In a separate bowl, whisk together all-purpose flour, baking soda, and salt.",
      "Gradually add the dry ingredients to the wet ingredients, mixing until just combined.",
      "Stir in chocolate chips.",
      "Drop rounded tablespoonfuls of dough onto ungreased baking sheets.",
      "Bake for 9-11 minutes or until golden brown around the edges.",
      "Allow cookies to cool on baking sheets for 5 minutes, then transfer to wire racks to cool completely.",
    ],
    image: PlaceholderImage,
    totalTime: 30,
    servings: 36,
    authenticity: 1,
    taste: 5,
    difficulty: 2,
    author: "Cookie Enthusiast",
    tags: ["cookies", "chocolate chip", "baking", "dessert"],
  },
];
