import PlaceholderImage from "./images/recipe-book.png";

export const Recipes = [
  // {
  //   {title: "Chicken Alfredo Pasta"},
  //   {description: "Chicken Alfredo Pasta is a creamy and indulgent Italian dish that combines tender chicken, fettuccine pasta, and a rich Alfredo sauce. It's a satisfying and comforting meal that the whole family will love."},
  //   {ingredients: [
  //   "8 ounces fettuccine pasta",
  //   "2 boneless, skinless chicken breasts",
  //   "2 tablespoons olive oil",
  //   "3 cloves garlic, minced",
  //   "1 cup heavy cream",
  //   "1/2 cup grated Parmesan cheese",
  //   "Salt and pepper to taste",
  //   "Chopped parsley for garnish",
  //   ]},
  //   {instructions: [
  //   "Cook fettuccine pasta according to package instructions. Drain and set aside.",
  //   "Season chicken breasts with salt and pepper.",
  //   "Heat olive oil in a large skillet over medium-high heat. Add chicken breasts and cook until browned and cooked through, about 6-8 minutes per side. Remove from skillet and let rest.",
  //   "In the same skillet, add minced garlic and cook until fragrant, about 1 minute.",
  //   "Reduce heat to low and pour in heavy cream. Stir in grated Parmesan cheese until melted and smooth.",
  //   "Slice cooked chicken breasts and add them back to the skillet. Cook for an additional 2-3 minutes to heat through.",
  //   "Add cooked fettuccine pasta to the skillet and toss to coat with the Alfredo sauce.",
  //   "Garnish with chopped parsley and serve hot.",
  //   ]},
  //   {imageURL: "https://images.unsplash.com/photo-1597645587824-c484d8b5e505?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y2hpY2tlbiUyMGFsZnJlc2h8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60"},
  //   {totalTime: 40},
  //   {servings: 4},
  //   {authenticity: 3},
  //   {taste: 5},
  //   {difficulty: 2},
  //   {author: "Italian Food Lover"},
  //   {tags: ["pasta", "chicken", "alfredo", "italian"]},
  //   },
    
    {
    title: "Greek Salad",
    description: "Greek Salad is a refreshing and healthy salad that features crisp vegetables, tangy feta cheese, and a simple vinaigrette dressing. It's a perfect side dish for any Mediterranean-inspired meal or a light and satisfying main course on its own.",
    ingredients: [
    "2 cups cherry tomatoes, halved",
    "1 cucumber, diced",
    "1 bell pepper, diced",
    "1/2 red onion, thinly sliced",
    "1/2 cup Kalamata olives, pitted",
    "1/2 cup crumbled feta cheese",
    "2 tablespoons extra virgin olive oil",
    "1 tablespoon red wine vinegar",
    "1 teaspoon dried oregano",
    "Salt and pepper to taste",
    ],
    instructions: [
    "In a large bowl, combine cherry tomatoes, cucumber, bell pepper, red onion, Kalamata olives, and crumbled feta cheese.",
    "In a small bowl, whisk together extra virgin olive oil, red wine vinegar, dried oregano, salt, and pepper to make the dressing.",
    "Pour the dressing over the salad and toss to coat the vegetables.",
    "Refrigerate for at least 30 minutes to allow the flavors to meld.",
    "Serve chilled as a refreshing and healthy salad.",
    ],
    imageURL: "https://images.unsplash.com/photo-1516684667865-592aebca4e41?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60",
    totalTime: 15,
    servings: 4,
    authenticity: 2,
    taste: 4,
    difficulty: 1,
    author: "Healthy Eater",
    tags: ["salad", "greek", "vegetarian", "healthy"],
    },
    
    {
    title: "Beef Stir-Fry",
    description: "Beef Stir-Fry is a quick and flavorful dish that combines tender strips of beef, crisp vegetables, and a savory sauce. It's a versatile recipe that can be customized with your favorite vegetables and served over rice or noodles.",
    ingredients: [
    "1 pound beef sirloin, thinly sliced",
    "2 tablespoons soy sauce",
    "2 tablespoons oyster sauce",
    "1 tablespoon hoisin sauce",
    "1 tablespoon cornstarch",
    "1/2 teaspoon sesame oil",
    "2 tablespoons vegetable oil",
    "3 cloves garlic, minced",
    "1 bell pepper, thinly sliced",
    "1 cup broccoli florets",
    "1 cup snow peas",
    "1 carrot, julienned",
    "Salt and pepper to taste",
    "Sliced green onions for garnish",
    ],
    instructions: [
    "In a bowl, combine soy sauce, oyster sauce, hoisin sauce, cornstarch, and sesame oil. Mix well to make the sauce.",
    "Heat vegetable oil in a large skillet or wok over high heat.",
    "Add minced garlic and cook until fragrant, about 1 minute.",
    "Add beef slices to the skillet and stir-fry until browned and cooked to your liking. Remove beef from the skillet and set aside.",
    "In the same skillet, add bell pepper, broccoli florets, snow peas, and julienned carrot. Stir-fry until vegetables are crisp-tender.",
    "Return beef to the skillet and pour the sauce over the ingredients.",
    "Cook for an additional 1-2 minutes, stirring constantly, until the sauce thickens and coats the beef and vegetables.",
    "Season with salt and pepper to taste.",
    "Garnish with sliced green onions and serve hot over rice or noodles.",
    ],
    imageURL: "https://images.unsplash.com/photo-1578873286126-10b161651ce7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmVlZiUyMHN0aXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60",
    totalTime: 25,
    servings: 4,
    authenticity: 2,
    taste: 4,
    difficulty: 3,
    author: "Asian Cuisine Lover",
    tags: ["beef", "stir-fry", "asian", "dinner"],
    },
    
    {
    title: "Avocado Toast",
    description: "Avocado Toast is a simple yet delicious breakfast or brunch option that has gained popularity for its creamy avocado topping and endless topping variations. It's a nutritious and satisfying way to start your day.",
    ingredients: [
    "2 slices whole grain bread, toasted",
    "1 ripe avocado, peeled and pitted",
    "1 tablespoon lemon juice",
    "Salt and pepper to taste",
    "Optional toppings: sliced cherry tomatoes, crumbled feta cheese, red pepper flakes, microgreens, poached egg",
    ],
    instructions: [
    "In a small bowl, mash the ripe avocado with a fork until smooth.",
    "Add lemon juice, salt, and pepper to taste. Mix well.",
    "Spread the mashed avocado mixture evenly onto the toasted bread slices.",
    "Top with your desired toppings, such as sliced cherry tomatoes, crumbled feta cheese, red pepper flakes, microgreens, or a poached egg.",
    "Serve immediately and enjoy the creamy and flavorful avocado toast.",
    ],
    imageURL: "https://images.unsplash.com/photo-1512568400618-27f81f68eac9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60",
    totalTime: 10,
    servings: 1,
    authenticity: 1,
    taste: 4,
    difficulty: 1,
    author: "Breakfast Lover",
    tags: ["breakfast", "brunch", "avocado", "toast"],
    },
    
    {
    title: "Mediterranean Baked Salmon",
    description: "Mediterranean Baked Salmon is a healthy and flavorful dish that combines salmon fillets with a medley of Mediterranean-inspired ingredients. It's a simple and elegant seafood recipe that is perfect for a weeknight dinner or special occasions.",
    ingredients: [
    "4 salmon fillets",
    "2 tablespoons olive oil",
    "1 tablespoon lemon juice",
    "3 cloves garlic, minced",
    "1 teaspoon dried oregano",
    "1/2 teaspoon dried thyme",
    "1/2 teaspoon dried rosemary",
    "1/2 cup cherry tomatoes, halved",
    "1/4 cup pitted Kalamata olives, halved",
    "2 tablespoons crumbled feta cheese",
    "Salt and pepper to taste",
    "Chopped fresh parsley for garnish",
    ],
    instructions: [
    "Preheat oven to 400°F (200°C).",
    "In a small bowl, combine olive oil, lemon juice, minced garlic, dried oregano, dried thyme, and dried rosemary to make a marinade.",
    "Place salmon fillets in a baking dish and pour the marinade over the fillets. Ensure that the fillets are coated evenly.",
    "Arrange cherry tomatoes and Kalamata olives around the salmon fillets.",
    "Sprinkle crumbled feta cheese over the top of the salmon and vegetables.",
    "Season with salt and pepper to taste.",
    "Bake in the preheated oven for 12-15 minutes or until the salmon is cooked to your desired doneness.",
    "Garnish with chopped fresh parsley and serve hot.",
    ],
    imageURL: "https://images.unsplash.com/photo-1585457818760-6c5f8786f96c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fHNhbW9ufGVufDB8fDB8&auto=format&fit=crop&w=800&q=60",
    totalTime: 25,
    servings: 4,
    authenticity: 2,
    taste: 5,
    difficulty: 2,
    author: "Seafood Lover",
    tags: ["salmon", "baked", "mediterranean", "dinner"],
    }
];
